#!/bin/bash

function new-session()
{
    read -p "Enter a name for the session: " session_name
    exec tmux new -s "${session_name}"
}

function tmux-session()
{
  [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
  if [ $1 ]; then
    tmux $change -t "$1" 2>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1"); return
  fi
  session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0) && exec tmux $change -t "$session" || new-session
}

tmux-session
